# Generated by Django 5.0.6 on 2024-07-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Editorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=300)),
                ("ciudad", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=100)),
                ("codigo_postal", models.CharField(max_length=20)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("sitio_web", models.URLField()),
                ("fecha_fundacion", models.DateField()),
            ],
        ),
    ]
