# Generated by Django 5.0.7 on 2024-08-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_commentario_contact_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contactado",
            field=models.BooleanField(
                default=False, verbose_name="¿Se ha contactado con él?"
            ),
        ),
    ]
