services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: django_user_db
      MYSQL_PASSWORD: django_user_pass
    ports:
      - "3306:3306"
