# Generated by Django 5.0.7 on 2024-08-02 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título del curso"),
                ),
                ("content", models.TextField(verbose_name="Contenido del curso")),
                ("call_link", models.URLField(verbose_name="Enlace de llamada")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha y hora de creación",
                    ),
                ),
            ],
        ),
    ]
