# Generated by Django 5.0.7 on 2024-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="show_home",
            field=models.BooleanField(default=False, verbose_name="Mostrar en la home"),
        ),
    ]
