# Generated by Django 5.0.7 on 2024-08-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_show_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="toc",
            field=models.FileField(
                blank=True, null=True, upload_to="courses/toc/", verbose_name="Temario"
            ),
        ),
    ]
