# Generated by Django 5.0.7 on 2024-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_toc"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="courses/images/",
                verbose_name="Portada del curso",
            ),
        ),
    ]
