# Generated by Django 5.0.7 on 2024-08-07 11:26

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_course_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=thumbnails.fields.ImageField(
                blank=True,
                null=True,
                upload_to="courses/images/",
                verbose_name="Portada del curso",
            ),
        ),
    ]
