# Generated by Django 5.0.6 on 2024-06-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="edad",
            field=models.IntegerField(default=18),
        ),
    ]
