# Generated by Django 5.0.6 on 2024-06-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_person_edad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="id",
        ),
        migrations.AddField(
            model_name="person",
            name="dni",
            field=models.CharField(
                default="", max_length=9, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="edad",
            field=models.IntegerField(
                default=18, help_text="Introduce tu edad en formato número"
            ),
        ),
    ]
