# Generated by Django 5.0.6 on 2024-06-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_remove_person_family_person_family"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["age"]},
        ),
    ]
