# Generated by Django 5.0.6 on 2024-06-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_person_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name": "Familia", "verbose_name_plural": "Familias"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["age"],
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
            },
        ),
        migrations.AlterField(
            model_name="family",
            name="name",
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
