# Generated by Django 5.0.6 on 2024-06-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0005_alter_person_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="apellido",
            field=models.CharField(max_length=30, verbose_name="Apellidos"),
        ),
        migrations.AlterField(
            model_name="person",
            name="dni",
            field=models.CharField(max_length=9, unique=True, verbose_name="DNI"),
        ),
        migrations.AlterField(
            model_name="person",
            name="edad",
            field=models.IntegerField(
                default=18,
                help_text="Introduce tu edad en formato número",
                verbose_name="Edad",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="nombre",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
    ]
