# Generated by Django 5.0.6 on 2024-07-04 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_autor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("fecha_publicacion", models.DateField()),
                ("numero_paginas", models.IntegerField()),
                ("idioma", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("genero", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("autores", models.ManyToManyField(to="books.autor")),
                (
                    "editorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.editorial",
                    ),
                ),
            ],
        ),
    ]
