# Generated by Django 5.0.6 on 2024-07-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_libro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="idioma",
            field=models.CharField(
                choices=[("ES", "Español"), ("EN", "Inglés")], max_length=2
            ),
        ),
    ]
