# Generated by Django 5.0.6 on 2024-08-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_editorial_ciudad_alter_editorial_codigo_postal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorial",
            name="direccion",
            field=models.CharField(default="ejemplo", max_length=300),
            preserve_default=False,
        ),
    ]
