# Generated by Django 5.0.6 on 2024-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_alter_libro_autores_alter_libro_descripcion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="premios",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autor",
            name="sitio_web",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="autor",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
