# Generated by Django 5.0.6 on 2024-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_editorial_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="descripcion_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="libro",
            name="descripcion_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="libro",
            name="titulo_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="libro",
            name="titulo_es",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
