# Generated by Django 5.0.6 on 2024-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_alter_libro_autores"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="is_out_of_stock",
            field=models.BooleanField(
                default=False, verbose_name="Está fuera de stock"
            ),
        ),
    ]
