# Generated by Django 5.0.6 on 2024-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_editorial_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorial",
            name="level",
            field=models.CharField(
                choices=[("1", "Nivel 1"), ("2", "Nivel 2"), ("3", "Nivel 3")],
                default="1",
                max_length=2,
                verbose_name="Nivel",
            ),
        ),
    ]
